line_arbiter:
  - prefix: "PMPS:LFE:"
fastfaults:
  - prefix: "PMPS:LFE:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

preemptive_requests:
  - prefix: ""
    arbiter_instance: "Arbiter:01"
    assertion_pool_start: 0
    assertion_pool_end: 20
