line_arbiter_prefix: "PMPS:KFE:"
undulator_kicker_rate_pv: "IOC:BSY0:MP01:BYKIKS_RATE"
accelerator_mode_pv: "SIOC:FEES:MP01:FACMODE_RBV"
trans_req_pv: "AT1K0:GAS:TRANS_REQ_RBV"
trans_rbv_pv: "AT1K0:GAS:TRANS_RBV"

dashboard_url: "http://ctl-logsrv01:3000/ctl/grafana/d/PRr2cuGGz/k-pmps-events?viewPanel=2&orgId=1&refresh=10s&kiosk"

fastfaults:
  - name: "KFE Arbiter"
    prefix: "PMPS:KFE:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "KFE GATT"
    prefix: "PLC:KFE:GATT:"
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 75

  - name: "KFE Vacuum"
    prefix: "PLC:KFE:VAC:K0:"
    ffo_start: 1
    ffo_end: 5
    ff_start: 1
    ff_end: 20

  - name: "TMO Vacuum"
    prefix: "PLC:TMO:VAC:"
    ffo_start: 1
    ffo_end: 6
    ff_start: 1
    ff_end: 50

  - name: "TMO Optics"
    prefix: "PLC:TMO:OPTICS:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "TMO CC Motion"
    prefix: "PLC:TMO:MOTION:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 200

  - name: "KFE CC Motion"
    prefix: "PLC:KFE:MOTION:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "RIX Optics"
    prefix: "PLC:RIX:OPTICS:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "RIX Vacuum"
    prefix: "PLC:KFE:RIX:VAC:K2:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "RIX CC Motion"
    prefix: "PLC:RIX:MOTION:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 200

  - name: "CRIX Vacuum"
    prefix: "PLC:CRIXS:VAC:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "CRIX Motion"
    prefix: "PLC:CRIX:MOT:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50


preemptive_requests:
  - prefix: "PMPS:KFE:"
    arbiter_instance: "Arbiter:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:MOTION:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:MOTION:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:VAC:K0:"
    arbiter_instance: "Arb:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:GATT:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:GATT:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TMO:OPTICS:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TMO:OPTICS:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TMO:MOTION:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TMO:MOTION:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TMO:VAC:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TMO:VAC:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:RIX:OPTICS:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:RIX:OPTICS:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:RIX:MOTION:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 50

  - prefix: "PLC:RIX:MOTION:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:RIX:VAC:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:KFE:RIX:VAC:"
    arbiter_instance: "ARB:02"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:CRIXS:VAC:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:CRIX:MOT:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20
