line_arbiter_prefix: "PMPS:KFE:"
undulator_kicker_rate_pv: "IOC:BSY0:MP01:BYKIKS_RATE"

dashboard_url: "http://ctl-logsrv01:3000/ctl/grafana/d/PRr2cuGGz/k-pmps-events?orgId=1&refresh=10s&kiosk"

fastfaults:
  - prefix: "PMPS:KFE:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - prefix: "PLC:KFE:GATT:"
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 50

  - prefix: "PLC:KFE:VAC:K0:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - prefix: "PLC:TMO:VAC:"
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 50

  - prefix: "PLC:TMO:OPTICS:"
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 50

  - prefix: "PLC:KFE:MOTION:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

preemptive_requests:
  - prefix: "PMPS:KFE:"
    arbiter_instance: "Arbiter:01"
    assertion_pool_start: 0
    assertion_pool_end: 20
   
  - prefix: "PLC:KFE:MOTION:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 0
    assertion_pool_end: 20
