line_arbiter_prefix: "PMPS:LFE:"
undulator_kicker_rate_pv: "IOC:BSY0:MP01:BYKIK_RATE"
accelerator_mode_pv: "SIOC:FEEH:MP01:FACMODE_RBV"
trans_req_pv: "PMPS:LFE:RequestedBP:Transmission_RBV"
trans_rbv_pv: "PMPS:LFE:CurrentBP:Transmission_RBV"

dashboard_url: "http://ctl-logsrv01:3000/ctl/grafana/d/PQBzCnmMz/l-pmps-events?refresh=10s&kiosk"


fastfaults:
  - name: "LFE Arbiter"
    prefix: "PMPS:LFE:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "LFE Vacuum"
    prefix: "PLC:LFE:VAC:"
    ffo_start: 1
    ffo_end: 3
    ff_start: 1
    ff_end: 50

  - name: "LFE GEM"
    prefix: "PLC:LFE:GEM:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "LFE CC Motion"
    prefix: "PLC:LFE:MOTION:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "LFE Optics"
    prefix: "PLC:LFE:OPTICS:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "XRT Optics"
    prefix: "PLC:XRT:OPTICS:"
    ffo_start: 1
    ffo_end: 2
    ff_start: 1
    ff_end: 50

  - name: "TXI CC Motion"
    prefix: "PLC:TXI:MOTION:"
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 50

  - name: "TXI LFE VAC"
    prefix: "PLC:TXI:HXR:VAC:"
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 50

  - name: "TXI L1 VAC"
    prefix: "PLC:TXI:HXR:VAC:L1"
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 50

  - name: "TXI LFE Optics"
    prefix: "PLC:TXI:LFE:OPTICS:"
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 50


preemptive_requests:
  - prefix: "PMPS:LFE:"
    arbiter_instance: "Arbiter:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:LFE:MOTION:"
    arbiter_instance: "ARB"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:LFE:OPTICS:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:XRT:OPTICS:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TXI:MOTION:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20

  - prefix: "PLC:TXI:VAC:"
    arbiter_instance: "ARB:01"
    assertion_pool_start: 1
    assertion_pool_end: 20
