line_arbiter_prefix: "PMPS:TST:"
undulator_kicker_rate_pv: "PMPS:TST:BYKIK_RATE"
accelerator_mode_pv: "PMPS:TST:LCLSMODE_RBV"
trans_req_pv: "AT1K0:GAS:TRANS_REQ_RBV"
trans_rbv_pv: "AT1K0:GAS:TRANS_RBV"

dashboard_url: "about:new"


fastfaults:
  - prefix: "PLC:TST:MOT:"
    ffo_start: 1
    ffo_end: 1
    ff_start: 1
    ff_end: 50

preemptive_requests:
  - prefix: "PLC:TST:MOT:"
    arbiter_instance: "ARB"
    assertion_pool_start: 1
    assertion_pool_end: 20
